In [2]:
import pandas as pd
import os
import json

In [3]:
folder_path = r"C:\Users\Johnk\Documents\PhD\Quantum Computing Code\Quantum-Computing\SUSY\SUSY QM\PennyLane\ADAPT-VQE\Files"
folders = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]

In [6]:
cut_off_list = [2, 4, 8, 16, 32, 64]

potentials = []
cutoffs = []
basis_states = []
op_lists = []
min_e_exact = []
min_e = []

for f in folders:
    for cutoff in cut_off_list:
        data_path = folder_path + "\\{}\\{}_{}.json".format(f,f, cutoff)
                
        with open(data_path, 'r') as file:
            data = json.load(file)

        potentials.append(data['potential'])
        cutoffs.append(data['cutoff'])
        basis_states.append(data['basis_state'])
        op_lists.append(data['op_list'])
        min_e_exact.append(data['min_e_exact'])
        min_e.append(data['min_e'])

In [20]:
df = {"potentials":potentials,
    "cutoffs":cutoffs,
    "basis_states":basis_states,
    "op_lists":op_lists,
    "min_e_exact":min_e_exact,
    "min_e":min_e}

In [13]:
df = pd.DataFrame(df)
df

,potentials,cutoffs,basis_states,op_lists,min_e_exact,min_e
0,AHO,2,"[1, 0]",[Y(0)],-4.375000e-01,-4.375000e-01
1,AHO,4,"[1, 0, 0]",[Y(1)],-1.647853e-01,-1.647853e-01
2,AHO,8,"[1, 0, 0, 0]",[Y(1)],3.201011e-02,3.201011e-02
3,AHO,16,"[1, 0, 0, 0, 0]",[Y(2)],-1.166976e-03,-1.166976e-03
4,AHO,32,"[1, 0, 0, 0, 0, 0]",[Y(3)],6.182236e-06,6.182238e-06
5,AHO,64,"[1, 0, 0, 0, 0, 0, 0]",[Y(4)],-1.946443e-08,-1.944757e-08
6,DW,2,"[0, 0]",[Y(1)],3.572330e-01,3.572330e-01
7,DW,4,"[1, 0, 0]",[Y(1)],9.065599e-01,9.065599e-01
8,DW,8,"[0, 0, 0, 0]",[Y(3)],8.845804e-01,8.845804e-01
9,DW,16,"[0, 0, 0, 0, 0]",[Y(4)],8.915994e-01,8.915994e-01
10,DW,32,"[0, 0, 0, 0, 0, 0]",[Y(5)],8.916324e-01,8.916324e-01
11,DW,64,"[0, 0, 0, 0, 0, 0, 0]",[Y(6)],8.916324e-01,8.916324e-01
12,QHO,2,"[1, 0]",[Y(0)],0.000000e+00,0.000000e+00
13,QHO,4,"[1, 0, 0]",[Y(0)],0.000000e+00,0.000000e+00
14,QHO,8,"[1, 0, 0, 0]",[Y(0)],0.000000e+00,0.000000e+00
15,QHO,16,"[1, 0, 0, 0, 0]",[Y(0)],0.000000e+00,0.000000e+00
16,QHO,32,"[1, 0, 0, 0, 0, 0]",[Y(0)],0.000000e+00,0.000000e+00
17,QHO,64,"[1, 0, 0, 0, 0, 0, 0]",[Y(0)],0.000000e+00,0.000000e+00

In [19]:
from tabulate import tabulate

In [25]:
latex_table = tabulate(df, headers="keys", tablefmt="latex", floatfmt=".12f")
print(latex_table)

\begin{tabular}{lrllrr}
\hline
 potentials   &   cutoffs & basis\_states          & op\_lists   &     min\_e\_exact &           min\_e \\
\hline
 AHO          &         2 & [1, 0]                & ['Y(0)']   & -0.437500000000 & -0.437500000000 \\
 AHO          &         4 & [1, 0, 0]             & ['Y(1)']   & -0.164785260685 & -0.164785260685 \\
 AHO          &         8 & [1, 0, 0, 0]          & ['Y(1)']   &  0.032010110009 &  0.032010110009 \\
 AHO          &        16 & [1, 0, 0, 0, 0]       & ['Y(2)']   & -0.001166975681 & -0.001166975681 \\
 AHO          &        32 & [1, 0, 0, 0, 0, 0]    & ['Y(3)']   &  0.000006182236 &  0.000006182238 \\
 AHO          &        64 & [1, 0, 0, 0, 0, 0, 0] & ['Y(4)']   & -0.000000019464 & -0.000000019448 \\
 DW           &         2 & [0, 0]                & ['Y(1)']   &  0.357233047034 &  0.357233047034 \\
 DW           &         4 & [1, 0, 0]             & ['Y(1)']   &  0.906559871474 &  0.906559871474 \\
 DW           &         8 & [0, 0, 0, 0]          & ['Y(3)']   &  0.884580443866 &  0.884580443866 \\
 DW           &        16 & [0, 0, 0, 0, 0]       & ['Y(4)']   &  0.891599362327 &  0.891599362327 \\
 DW           &        32 & [0, 0, 0, 0, 0, 0]    & ['Y(5)']   &  0.891632370555 &  0.891632370555 \\
 DW           &        64 & [0, 0, 0, 0, 0, 0, 0] & ['Y(6)']   &  0.891632380137 &  0.891632380137 \\
 QHO          &         2 & [1, 0]                & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
 QHO          &         4 & [1, 0, 0]             & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
 QHO          &         8 & [1, 0, 0, 0]          & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
 QHO          &        16 & [1, 0, 0, 0, 0]       & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
 QHO          &        32 & [1, 0, 0, 0, 0, 0]    & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
 QHO          &        64 & [1, 0, 0, 0, 0, 0, 0] & ['Y(0)']   &  0.000000000000 &  0.000000000000 \\
\hline
\end{tabular}